source("https://bioconductor.org/biocLite.R")
update.packages(ask=F)
install.packages("devtools")
#biocLite("Simon-Coetzee/StatePaintR", suppressUpdates = TRUE, dependencies = TRUE)
#biocLite("Simon-Coetzee/funciVar", suppressUpdates = TRUE, dependencies = TRUE)
#biocLite("Simon-Coetzee/motifbreakR", suppressUpdates = TRUE, dependencies = TRUE)
#biocLite("SNPlocs.Hsapiens.dbSNP144.GRCh37")
#biocLite("BSgenome.Hsapiens.UCSC.hg19")
biocLite("TCGAbiolinksGUI")
biocLite("TCGAWorkflowData")
install.packages("formatR")
install.packages("UpSetR")
install.packages("roxygen2")
devtools::install_github("BioinformaticsFMRP/TCGAbiolinks", dependencies = TRUE)
devtools::install_github("BioinformaticsFMRP/TCGAbiolinks.data",ref = "R_3.4", dependencies = TRUE)
devtools::install_github("BioinformaticsFMRP/TCGAbiolinksGUI", dependencies = TRUE)
devtools::install_github("tiagochst/ELMER", dependencies = TRUE)
devtools::install_github("tiagochst/ELMER.data", dependencies = TRUE)
#devtools::install_github("Bioconductor-mirror/VariantAnnotation",ref = "release-3.5", force = T)
#devtools::install_github("Simon-Coetzee/Bioc2017", dependencies = TRUE , build_vignettes = TRUE)
biocLite("BioinformaticsFMRP/Bioc2017.TCGAbiolinks.ELMER",
         dependencies = TRUE, build_vignettes = TRUE)
