source("https://bioconductor.org/biocLite.R")
biocLite("minfi")
biocLite("TCGAbiolinksGUI")
biocLite("TCGAWorkflowData")
devtools::install_github("BioinformaticsFMRP/TCGAbiolinks", dependencies = TRUE)
devtools::install_github("BioinformaticsFMRP/TCGAbiolinks.data",ref = "R_3.4", dependencies = TRUE)
devtools::install_github("BioinformaticsFMRP/TCGAbiolinksGUI", dependencies = TRUE)
devtools::install_github("tiagochst/ELMER", dependencies = TRUE)
devtools::install_github("tiagochst/ELMER.data", dependencies = TRUE)
