install.packages("devtools")
devtools::install_github("tiagochst/ELMER", ask=F, dependencies = TRUE)
devtools::install_github("tiagochst/ELMER.data", ask=F)
devtools::install_github("BioinformaticsFMRP/TCGAbiolinks", ask=F, dependencies = TRUE)
devtools::install_github("BioinformaticsFMRP/TCGAbiolinksGUI.data",ref = "R_3.4", ask=F, dependencies = TRUE)
devtools::install_github("BioinformaticsFMRP/TCGAbiolinksGUI", ask=F, dependencies = TRUE)
source("http://bioconductor.org/biocLite.R")
#biocLite("methylumi")
#devtools::install("/tmp/TCGAWorkflowData/")
#devtools::install("/tmp/TCGAWorkflow/")
#devtools::install_github("BioinformaticsFMRP/TCGAWorkflowData")
#devtools::install_github("BioinformaticsFMRP/TCGAWorkflow", dependencies = TRUE)
